development:
  adapter: redis
  url: redis://default:Bd3JIlt53cnZril7ukYG@containers-us-west-172.railway.app:6513
  channel_prefix: rails-chat_development

test:
  adapter: async

production:
  adapter: redis
  url: redis://default:Bd3JIlt53cnZril7ukYG@containers-us-west-172.railway.app:6513
  channel_prefix: rails-chat_production
