development:
  adapter: redis
  url: <%= ENV.fetch("at_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: rails-chat-_development

test:
  adapter: async

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: rails-chat-_production
