default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= Rails.application.credentials.dig(:development, :username) %>
  password: <%= Rails.application.credentials.dig(:development, :password) %>
  host: 159.223.36.26

development:
  <<: *default
  database: webchatapp-rails

test:
  <<: *default
  database: webchatapp-rails

production:
  <<: *default
  database: webchatapp-rails
