default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: rails
  password: aaf12bd76e3f9002921cd148f7fd139f
  host: 161.35.225.109

development:
  <<: *default
  database: webchatapp-rails

test:
  <<: *default
  database: webchatapp-rails

production:
  <<: *default
  database: webchatapp-rails
